### ISSUE TITLE
Drop node12 support

### ISSUE THREAD

**Issue by Kikobeats** [vercel/edge-runtime#133]
We are supporting node12 essentially because it's the minimum Node.js version supported by Next.js.

The moment that changes, we can:

- [ ] Upgrade jest@28 to jest@29
- [ ] Update esbuild [target](https://github.com/vercel/edge-runtime/blob/50448d2b70f3be204ea776cdfe1d7580c113debd/packages/primitives/scripts/build.ts#L26) to the new target
- [ ] Remove node12 from [docs](https://github.com/vercel/edge-runtime/blob/1dff3331def64a803d801ab506970407717efa89/docs/pages/features/polyfills.mdx)
- [ ] Remove [uuid](https://github.com/vercel/edge-runtime/blob/6d4341cda9a0e692c4991983279a0e8522662b77/packages/primitives/src/primitives/crypto.js#L8) polyfill
- [ ] Remove [http](https://github.com/vercel/edge-runtime/blob/main/packages/primitives/src/patches/http.js) missing methods.
- [ ] Remove [util](https://github.com/vercel/edge-runtime/blob/main/packages/primitives/src/patches/util-types.js) missing methods.
- [ ] Remove [buffer <-> blob](https://github.com/vercel/edge-runtime/blob/main/packages/primitives/src/patches/buffer.js) patch.
- [ ] Remove [AbortSignal workaround for Jest](https://github.com/vercel/edge-runtime/pull/95/commits/da4e12242c99664596636cfba31034fc528312e6).

**Comment by styfle** [comment]
Let's go ahead and ship this now that Next.js just landed:

- https://github.com/vercel/next.js/pull/41150
