### ISSUE TITLE
@edge-runtime/types: Missing some types

### ISSUE THREAD

**Issue by alii** [vercel/edge-runtime#138]
**Current behavior**

<img width="400" alt="CleanShot 2022-09-20 at 18 36 11@2x" src="https://user-images.githubusercontent.com/25351731/191326287-364cdf80-7c8e-4519-a0fb-b43f7e512692.png">

With the following TSConfig, a lot of things are missing in the types:

```json
{
	"compilerOptions": {
		"moduleResolution": "NodeNext",
		"module": "NodeNext",
		"strict": true,
		"useUnknownInCatchVariables": true,
		"noImplicitOverride": true,
		"noFallthroughCasesInSwitch": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"exactOptionalPropertyTypes": true,
		"noImplicitReturns": true,
		"noUncheckedIndexedAccess": true,
		// Explicitly empty lib (no DOM, etc)
		"lib": [],
		// Only specify types for edge-runtime
		"types": ["@edge-runtime/types"]
	}
}
```

Here's a couple things that don't exist. Perhaps I need to include some other types to "lib" but for example `addEventListener` exists in DOM but a lot of things that exist in DOM do not exist in the edge-runtime.

**Expected behavior**

Every Edge Runtime API should to have types exposed properly.

**Comment by Kikobeats** [comment]
Hey @alii, I'm taking care about this.

I reproduced the issue in this repo: https://github.com/Kikobeats/edge-runtime-138

It looks like `addEventListener` is defined, still some types are missing. Working into land a fix.
