### ISSUE TITLE
Deleting Headers Causing Immutable TypeErrors

### ISSUE THREAD

**Issue by hassanbazzi** [vercel/edge-runtime#168]
https://github.com/vercel/edge-runtime/blob/803cc4f062621bf96c7531cca3c6d62cdad9a846/packages/runtime/src/edge-runtime.ts#L155

Hey! Working on writing some middleware functions and I suddenly started getting `TypeError: Immutable` 

After some detective work, I found out it's because of the above 3 lines that try to delete these 3 headers when doing a redirection. When I delete these 3 lines locally, everything works as expected. Any idea what these 3 do or why this is happening? 

I also understand this hasn't been changed in quite some time, and so it might be something else that's causing this to happen under the hood, I just don't understand it enough and some guidance would be amazing.

I'm on vercel cli 28.4.8.

**Comment by Kikobeats** [comment]
Thanks for reporting @hassanbazzi

It's fixed in the latest Vercel CLI vhttps://github.com/vercel/vercel/releases/tag/vercel%4028.4.10 or above

![CleanShot 2022-10-13 at 10 22 33@2x](https://user-images.githubusercontent.com/2096101/195542908-137a6e7e-7564-4235-a03f-9217d7c24d97.png)
