### ISSUE TITLE
Expose a method for hot reloading

### ISSUE THREAD

**Issue by gffuma** [vercel/edge-runtime#20]
I think having a public method to expose "hot reloading" is useful.
Generally speaking this kind of sandboxes are great to implement great developer experience where the developer simply write code and have it executed and hot reloaded in the same "context" of an edge runtime.

So i think edge runtime is missing a method to hot reload the developer code.

Now i'm using this workaround but rely on internals and isn't so good:

```js
import { EdgeRuntime, runServer } from 'edge-runtime'

async function main() {
  const initialCode = `
addEventListener('fetch', event => {
  console.log('Call Fetch')
  return event.respondWith(new Response('Hello'))
})`

  const runtime = new EdgeRuntime({ initialCode })

  const server = await runServer({ runtime, port: 9000 })
  console.log('Listeing on', server.url)

  let i = 0
  // In real world this is an hook from a compilation step
  setInterval(() => {
    // WORKAROUND
    runtime.evaluate(`
      delete self.__listeners['fetch'];
    `)
    runtime.evaluate(`
      addEventListener('fetch', event => {
        console.log('Call Fetch ' + ${i})
        return event.respondWith(new Response('Hello ${i}'))
      })`)
    i++
  }, 1000)
}

main().catch((err) => {
  console.error(err)
})
```

**Comment by Kikobeats** [comment]
Hello,

The `runServer` is just there for debugging purpose; Ideally, we want to deprecate the edge-runtime CLI and implement the functionality as part of the [Vercel CLI](https://vercel.com/docs/cli).

Also, you can always reload out of the box, using [watchexec](https://github.com/watchexec/watchexec) or similar tools.

**Comment by IanMitchell** [comment]
I've implemented a developer environment into my framework based off of runServer where this functionality would help a lot - its a lot faster to run the posted workaround code here than it is to recreate the entire runtime.

**Comment by gffuma** [comment]
I agree with @IanMitchell. This also the way how https://github.com/cloudflare/miniflare works.

**Comment by IanMitchell** [comment]
Hey @Kikobeats, I just wanted to check in about the possibility of keeping `runServer` and exposing a hot reload system since it's been a bit - does it still go against the goals of the project, or would an outside contribution unblock it? 

I'm happy to explain more about my usage of `edge-runtime` in my project if it's helpful!
