### ISSUE TITLE
Can this deploy on Vercel without nextjs?

### ISSUE THREAD

**Issue by curiousweirdo** [vercel/edge-runtime#227]
How to deploy to Vercel, assume that I already have index.js that running the server via `const server = await runServer({ runtime })

I did try

- deploy via ```vercel deploy```
   - and I try to navigate to the deployed URL, it gives me 404 (as like my fetch event hasn't ran)

I don't know if I have to do some custom configuration on build config or something else. If someone know please clarify me this please thank you

NOTE: that it work completely fine on my local-machine

Thank you

**Comment by feugy** [comment]
Hello @curiousweirdo.
Vercel has it's own "flavor" of the edge runtime, called [edge functions](https://vercel.com/docs/concepts/functions/edge-functions). You don't deploy the whole runtime on Vercel: you put a file that exports your function, and Vercel runs it on the edge:

```js
// file api/my-function.js, this will become https://xyz.vercel.app/api/my-function

export const config = { runtime: 'edge' };

export default (req: Request) => {
  return new Response(`Hello, from ${req.url} I'm now an Edge Function!`);
};
```

Hope it'll help.
