### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by michealroberts** [vercel/edge-runtime#266]
## Bug Report

**Current behavior**

A clear and concise description of the behavior.

I have a minimum reproduction of the issue I am facing here: https://github.com/michealroberts/vercel-trpc-prisma

Essentially, I am trying to run a tRPC server on the vercel edge runtime (as given here: https://trpc.io/docs/fetch#vercel-edge-runtime) from a starter repo here https://github.com/trpc/trpc/tree/main/examples/vercel-edge-runtime by @KATT AND @QuiiBz.

I have managed to get it running locally by hard-setting the prisma datasource to a prisma studio proxy connection as shown here:

<img width="555" alt="Screenshot 2023-02-15 at 13 50 56" src="https://user-images.githubusercontent.com/84131395/219045695-8a55d96f-086a-4ea4-8e35-55c3869a2e59.png">

<img width="632" alt="Screenshot 2023-02-15 at 13 51 05" src="https://user-images.githubusercontent.com/84131395/219045731-14e2ab3d-7b3b-478a-b876-932882886c88.png">

I have since tried to replace the datasource with my hardset proxy URL with `process.env.DATABASE_URL` as follows:

```ts
import { PrismaClient } from '@prisma/client/edge'

export const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABSE_URL
    }
  }
})
```

But, alas, it does not work (with an exit code 1):

<img width="553" alt="Screenshot 2023-02-15 at 13 52 34" src="https://user-images.githubusercontent.com/84131395/219046102-fca55667-ddb5-4fde-b8e2-d23bf181536b.png">

**Expected behavior/code**

The expected behaviour would be once added any environment variables to `.env` in the project root, they should be injected into the runtime? Unless there is another way to inject process.env variables when running the edge-runtime server locally that I have missed?

**Comment by Kikobeats** [comment]
It's expected `process` is not defined since it's a Node.js API.

What you can do is to extend the context and defining it:

```js
import { EdgeRuntime } from 'edge-runtime'
 
const runtime = new EdgeRuntime({
  extend: (context) =>
  Object.assign(context, {
    process: { env: { NODE_ENV: 'development' } }
  })
})
```

See https://edge-runtime.vercel.app/getting-started#usage 🙂
