### ISSUE TITLE
Use `MPL-2.0` instead of `MPLv2` in `license` field

### ISSUE THREAD

**Issue by simon-mathewson** [vercel/edge-runtime#274]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We're using an automated license checking tool that requires the `license` field in `package.json` to be a valid [SPDX license expression](https://spdx.org/licenses/).

**Describe the solution you'd like**

Change `MPLv2` to `MPL-2.0` in all `package.json`s. 

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**

This will help users with automated license checking tools.

**Comment by Kikobeats** [comment]
A PR will be really appreciated!

**Comment by simon-mathewson** [comment]
Sure, I just opened this PR: #276

**Comment by codepunkt** [comment]
Thanks @Kikobeats!
