### ISSUE TITLE
Please upgrade webcrypto-core to solve invalid uuid bug

### ISSUE THREAD

**Issue by motopods** [vercel/edge-runtime#287]
## Bug Report

**Current behavior**

Invalid uuid generated.

**Expected behavior/code**

right uuid.

**Possible solution**

This bug has been fixed at 1.7.6 of webcrypto-core

https://github.com/PeculiarVentures/webcrypto-core/commit/049cd7c9434c6171d8d8f4c83c9aa912fd510d3f

**Additional context/screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Kikobeats** [comment]
Hello, correct me if I'm wrong, but `@peculiar/webcrypto` uses `webcrypto-core` 

https://github.com/PeculiarVentures/webcrypto/blob/master/package.json#L77

and the last version is already used:

```
$ npm why webcrypto-core

devDependencies:
@peculiar/webcrypto 1.4.1
└── webcrypto-core 1.7.6
```

Did you experience the bug using edge-runtime?

**Comment by motopods** [comment]
Sorry for that, it's next.js problem which doesn't use latest @edge-runtime/primitives version.
