### ISSUE TITLE
Support `Event` Web API

### ISSUE THREAD

**Issue by f-elix** [vercel/edge-runtime#293]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'm trying to deploy an edge function that uses the `stripe-node` package. Despite the name, it is possible to use it in other runtimes, such as Cloudflare workers and Deno. There is however a problem with Vercel edge functions because the `Event` API is not supported (see this issue: https://github.com/stripe/stripe-node/issues/1732). An error is thrown whenever the function is invoked.

You can reproduce the issue by deploying and edge function with the following code:

```ts
import Stripe from 'stripe';

const stripe = new Stripe(STRIPE_SECRET_KEY, {
	apiVersion: '2022-11-15',
	httpClient: Stripe.createFetchHttpClient()
});
```

**Describe the solution you'd like**
Support the [Event Web API](https://developer.mozilla.org/en-US/docs/Web/API/Event), as it is part of WinterCG's [Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/#index) proposal.

**Comment by thillmann** [comment]
I was able to get Stripe to work on Vercel's edge function by using a polyfill (`event-target-polyfill`) for the events api. This seems to work (at least for the way I'm using Stripe).

**Comment by f-elix** [comment]
@thillmann Thank you so much! All my edge functions using stripe-node now work :)

Still it would be nice if this could be added to Vercel's edge runtime.

**Comment by Kikobeats** [comment]
The Edge Runtime core is using `event-target-shim` which provides `Event` and `EventTarget` polyfills.

Maybe this was an issue in the future but it seems like it's available globally:

```
❯ edge-runtime --repl
ƒ => !!Event
true
ƒ => !!EventTarget
true
ƒ =>
```

can someone confirm it's fixed using the latest version? 🙂

**Comment by f-elix** [comment]
@Kikobeats, I tried again without `event-target-polyfill` and I am still getting the same error. 

The error is `TypeError: Class extends value undefined is not a constructor or null` because of an internal `stripe-node` class that extends `Event`, which means `Event` is still undefined at runtime without the polyfill. Hope that helps!

**Comment by Kikobeats** [comment]
@f-elix are you using Next.js or Vercel CLI?

Also, if you do `globalThis.Event` what you get? undefined?

**Comment by sundaycrafts** [comment]
I think this issue is still going on. Here is a error message from [stripe-node](https://github.com/stripe/stripe-node/blob/578de1b35a186ac186b4416bafad8c594b4e943e/src/StripeEmitter.ts#L19)

```
TypeError: EventTarget is not a constructor
    at (node_modules/stripe/esm/StripeEmitter.js:15:27)
    at (node_modules/stripe/esm/platform/WebPlatformFunctions.js:13:15)
    at (node_modules/stripe/esm/stripe.core.js:48:43)
    at (app/api/order_hook/route.ts:7:15)
    at (webpack/bootstrap:21:0)
    at (node_modules/luxon/src/datetime.js:2248:0)
    at (webpack/runtime/jsonp chunk loading:34:0)
    at (api/my_hook:middleware.js:1:17)
```

**Comment by f-elix** [comment]
@Kikobeats Sorry for the delay! I'm still getting the same error:

```sh
TypeError: Class extends value undefined is not a constructor or null
    at (../../../../node_modules/stripe/esm/StripeEmitter.js:6:6)
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:13:7)
    at (../../../../node_modules/stripe/esm/platform/WebPlatformFunctions.js:2:0)
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:13:7)
    at (../../../../node_modules/stripe/esm/stripe.esm.worker.js:1:0)
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/stripe.js:1:0)
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/entries/pages/_locale_lang_/_slug_slug_signup_/_page.server.ts.js:9:0)
    at (../../../../.svelte-kit/vercel-tmp/fn/edge.js:13:7)
```

**Comment by Kikobeats** [comment]
Hello,

The original issue reported support for `Event`, but I didn't note `EventTarget` should be added as well.

Now, both are working properly at production.

source code:

```
export const config = { runtime: 'edge' }

export default () => {
  return Response.json({
    queueMicrotask: !!queueMicrotask,
    Event: !!Event,
    EventTarget: !!EventTarget
  })
}
```

deployment: https://edge-api-one.vercel.app/api

I tested manually in a project running `npm i stripe` on the Edge, and it works flawless.

Can you confirm at your end? 🙂
