### ISSUE TITLE
Maximum number of env variables

### ISSUE THREAD

**Issue by ValentinH** [vercel/edge-runtime#303]
### Summary

While trying to move some of our API routes to the Edge runtime (as encouraged by Vercel), we faced this error during the Vercel build:
```
too_many_edge_functions_bindings: The Edge Function "api/test" contains too many environment variables + WASM bindings (limit=64, contains=65).
```

I couldn't find this limit documented anywhere, so did I miss it?

Here's more detail for other devs facing this error.
In our current setup, we have a shared `env.ts` file that reads all the env variables on startup and ensure they are correctly set. They are then exposed in a type-safe way. In this file, we have indeed more than 64 entries and removing some of them fixed this error. However, this limitation means that we would need to change the way we access env variables if we want to switch a route to the Edge Runtime.

**Comment by ValentinH** [comment]
Thanks to [the more flexible Env variables announced here:](https://vercel.com/changelog/more-flexible-environment-variables-in-edge-functions-and-middleware), I can confirm that this issue is gone 🎉

**Comment by Kikobeats** [comment]
Thanks to you for reporting this 🎉
