### ISSUE TITLE
`crypto.randomUUID()` generates an invalid UUID in `@edge-runtime/jest-environment`

### ISSUE THREAD

**Issue by keyz** [vercel/edge-runtime#310]
## Bug Report

**Current behavior**

When using `@edge-runtime/jest-environment`, `crypto.randomUUID()` generates an invalid UUID (only 35 characters)

repro: https://github.com/keyz/vercel-edge-runtime-vm-uuid-bug-repro

<img width="860" alt="image" src="https://user-images.githubusercontent.com/2268452/233898292-cc889f9f-d25a-458a-90b8-507b4fe51297.png">

**Expected behavior/code**

A valid v4 UUID gets generated per [spec](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)

**Comment by keyz** [comment]
This seems to be related: https://github.com/vercel/edge-runtime/issues/287

**Comment by Kikobeats** [comment]
Closing since the version was updated at Next.js time ago
