### ISSUE TITLE
Cookie does not support same name with different paths

### ISSUE THREAD

**Issue by motopods** [vercel/edge-runtime#341]
## Bug Report

**Current behavior**

Cookies are only stored in map by name, so same name cookie will be droped.

https://github.com/vercel/edge-runtime/blob/bf167c418247a79d3941bfce4a5d43c37f512502/packages/cookies/src/request-cookies.ts#L18

**Expected behavior/code**

Get all cookies by name with different paths.

And the order of cookies should be kept.

**Comment by JannikWempe** [comment]
+1

We want to update a domain of cookie by deleting and recreating it.

This does not work:
```
  response.cookies.set({
    name: COOKIE_NAME,
    value: '',
    domain: `.${host}`,
    httpOnly: true,
    maxAge: -1,
  });
  response.cookies.set({
    name: COOKIE_NAME,
    value,
    httpOnly: true,
    maxAge: 60 * 60,
  });
```

There is only a single `Set-Cookie` header in the response and the last `set` takes precedence.

This does work:
```
  response.headers.set(
    'Set-Cookie',
    `${COOKIE_NAME}=; HttpOnly; Max-Age=0; Path=/; Domain=.${host}, ${COOKIE_NAME}=${
      value
    }; HttpOnly; Max-Age=${60 * 60}; Path=/;`,
  );
```

Note: we are using Next 13.4.3.

**Comment by Kikobeats** [comment]
@motopods @JannikWempe Can you please reproduce the buggy behavior, pasting a code snippet that can be pasted at DevTools? 🙏

**Comment by Kikobeats** [comment]
I believe this is fixed by https://github.com/vercel/edge-runtime/commit/586de6e7bc7bb18121ed2853a4598077a46a21cf; consider commenting if not!
