### ISSUE TITLE
Support queueMicrotask() (polyfill locally)

### ISSUE THREAD

**Issue by andyjy** [vercel/edge-runtime#343]
## Feature Request

A library I'm using calls the web standard `queueMicrotask()`. Cloudflare Workers supports this so my code works when deployed as a Vercel Edge function, but fails locally under the Next.js `next dev` when running under the Edge Runtime.

**Describe the solution you'd like**
Polyfill (or otherwise support) `queueMicrotask()` under local development / when using the Edge Runtime.

**Describe alternatives you've considered**
..maybe there's a reason why this isn't supported already? (I understand that Cloudflare Workers is just one specific implementation; perhaps `queueMicrotask()` is purposefully not supported?)

My workaround is simply to polyfill manually for local development:

```
global.queueMicrotask = global.queueMicrotask || ((cb) => Promise.resolve().then(cb));
```

**Comment by Kikobeats** [comment]
Thanks for reporting @andyjy and really sorry for the delay.

The latest version exposed `queueMicrotask` globally 👏
