### ISSUE TITLE
Problems with inconsistent performance

### ISSUE THREAD

**Issue by mike183** [vercel/edge-runtime#39]
Hi, I've been experimenting with edge-runtime using Next 12.2's Edge Server-Rendering with Vercel and have been experiencing some performance issues.

The application itself is very simple, just outputting "Hello World" from the index page in Next.js (see code below)

```js
// pages/index.js
export default function Home() {
  return (
    <>
      Hello World!
    </>
  )
}
```

When loading this page via Vercel, I'm seeing response times ranging from 200-400ms, which in itself seems to be slower than I would expect.

This level of performance is consistent unless I repeatedly refresh the page, at which point response times begin to drop to 50-70ms, although this is sporadic and not very consistent.

I'm curious to know whether there is a real issue somewhere or whether I'm just doing something wrong.

You can find the deployed example application here, https://my-app-mike183.vercel.app/

Happy to share any further debug information that you might need 🙂

**Comment by mike183** [comment]
Thanks for clarifying @shuding! Is there anywhere that we can follow the progress of the performance work?

**Comment by shuding** [comment]
We are doing improvements directly to the Next.js repository, e.g.: https://github.com/vercel/next.js/pull/38570. But we don't have a specific thread to track it right now.

**Comment by mike183** [comment]
Thanks @shuding! I’ll close this issue since it’s seems to be more of a Next.js problem than edge-runtime.
