### ISSUE TITLE
Primitives: Use a better `AbortController` polyfill

### ISSUE THREAD

**Issue by Kikobeats** [vercel/edge-runtime#45]
The [abort-controller polyfill](https://github.com/mysticatea/abort-controller) used in edge-runtime isn't compliant with the spec right now, because:

- `AbortSignal.abort` is missing
- `AbortSignal.timeout` is missing

Alternatives:

- https://www.npmjs.com/package/abortcontroller-polyfill
- https://www.npmjs.com/package/yet-another-abortcontroller-polyfill

Related:

- https://github.com/vercel/next.js/issues/38658

**Comment by javivelasco** [comment]
https://linear.app/vercel/issue/EC-72/use-a-better-abortcontroller-polyfill
