### ISSUE TITLE
edge run time stop streaming on local machine after intense testing of ai framework

### ISSUE THREAD

**Issue by archywillhe** [vercel/edge-runtime#468]
## Bug Report

**Current behavior**

edge run time stop streaming on local machine after intense testing of ai framework

**Expected behavior/code**

edge run time should stream

**Additional context/screenshots**

It runs. But doesn't stream to client.

**Comment by Kikobeats** [comment]
Hello, can you make a code reproduction? A minimal repo containing the necessary code 🙏

**Comment by archywillhe** [comment]
oh thx for the lightning reply; actually i got it working with the latets vercel/ai version; but my own implementation that works locally doesnt work in production; 

e.g. this implementation also works locally but doesnt work in production :

```
https://github.com/wimluk/public-lib/tree/main/tutorials/How%20to%20Stream%20Real-Time%20OpenAI%20API%20Responses
```

**Comment by archywillhe** [comment]
could it be a versioning problem?

**Comment by Kikobeats** [comment]
@archywillhe is your production a Vercel deployment?

Can you check logs associated with your deployment? How they look? what errors are there?
