### ISSUE TITLE
Local Development Configuration

### ISSUE THREAD

**Issue by rossrobino** [vercel/edge-runtime#469]
## Questions & Answers

**Context of your question**

I'm just getting started using vercel edge-runtime. Here's my repo - https://github.com/rossrobino/func

I want to set up local development, I'm not sure if I'm doing this properly. When I run `vc dev` from my project directory and navigate to `http://localhost:3000/api/edge` I am getting this error in the console, although when I deploy it works fine. I'd like to ensure I'm setting up local dev correctly. Do I need to create a `dev` script in `package.json` calling the edge-runtime cli?  

I see [here](https://edge-runtime.vercel.app/#using-the-edge-runtime-locally) that the runtime will polyfill for local dev.

```
Property 'createCaches' does not exist on type 'typeof import(".../func/node_modules/@edge-runtime/primitives/types/index")'.

14   const createCaches: typeof Edge.createCaches
                                     ~~~~~~~~~~~~


Found 1 error in node_modules/@edge-runtime/types/src/index.d.ts:14
```

output upon navigating to the route locally (maybe this is correct?):

```
{
    "geo": {
        "region": "dev1"
    },
    "ip": "::1"
}
```

output when deployed:

```
{
    "geo": {
        "city": "...",
        "country": "US",
        "countryRegion": "MI",
        "region": "cle1",
        "latitude": "...",
        "longitude": "..."
    },
    "ip": "..."
}
```

Any pointers appreciated. I'd like to simulate the edge environment locally and want to make sure I'm doing it correctly.

**Comment by Kikobeats** [comment]
Thanks for reporting, it seems we forgot removed an unnecessary type.

I just released https://github.com/vercel/edge-runtime/releases/tag/%40edge-runtime/types%402.1.4, can you upgrade your dependency and tell me if that resolve your issue? 🙂

**Comment by rossrobino** [comment]
@Kikobeats it works! Thanks for your help.
