### ISSUE TITLE
`import.meta.url` is `undefined`

### ISSUE THREAD

**Issue by PonomareVlad** [vercel/edge-runtime#486]
## Bug Report

**Current behavior**

```js
// api/index.mjs

console.log(import.meta) // {}

console.log(import.meta.url) // undefined
```

At Edge Runtime `import.meta.url` is undefined.

**Expected behavior/code**

Expected specification-driven behavior:

```js
// api/index.mjs

console.log(import.meta) // {url: ".../api/index.mjs"}

console.log(import.meta.url) // ".../api/index.mjs"
```

**Possible solution**

Inject module urls in-place while compiling 🌚

**Additional context/screenshots**

In my project I use `import.meta.url` for auto-mapping many modules, that will accesses by pathname, like:

```js
// some/things/A.mjs

export const name = import.meta.url.split("/some/things/").pop() // "A.mjs"

export const handler = () => "result"
```

```js
// all.mjs

import A from "./some/things/A.mjs"
import B from "./some/things/B.mjs"
import C from "./some/things/C.mjs"

const modules = [A, B, C]

const repository = new Map()

modules.forEach(module => 
    repository.set(module.name, module.handler)
)

export const getHandler = name => repository.get(name)
```

```js
// consumer.mjs

import {getHandler} from "./all.mjs"

const handler = getHandler("A.mjs")

console.log(handler()) // "result"
```

**Comment by Kikobeats** [comment]
Hello, it seems the issue is actually in the top layer framework that uses Edge Runtime.

Can you please report it at [Vercel CLI](https://github.com/vercel/vercel) or [Next.js](https://github.com/vercel/next.js) repo' (depends on which one are you using) 🙏
