### ISSUE TITLE
`@edge-runtime/types` should declare global types for `fetch`, `File` etc

### ISSUE THREAD

**Issue by jedwards1211** [vercel/edge-runtime#506]
## Bug Report

**Current behavior**

```ts
/// <reference types="@edge-runtime/types" />

const response = await fetch(...) // ERROR: cannot fine name 'fetch'. ts(2304)
```

If anyone doesn't get this error, it's because they accidentally have TS types for a different environment.  That may allow people to be productive, but those types are bound to be inaccurate for the Edge Runtime environment.

Looking at the code, `@edge-runtime/types` gets types for things like `File` from elsewhere (I don't think `@types/node` provides it yet, does `@types/jest`?  I'm not sure where the `File` type is coming from)

**Expected behavior/code**

`/// <reference types="@edge-runtime/types" />` should put types and variable declarations for `fetch`, `File`, etc on global scope, just like `/// <reference lib="dom" />` does.

**Possible solution**

If `fetch.d.ts` is just re-exporting global classes provided by something else, it is necessary to re-export both the type and variable declaration like so:

```ts
declare const FileAlias: typeof File     // fetch.d.ts already has this by a different name
type FileAlias = File                              // but fetch.d.ts is missing this

export { FileAlias as File }
```

And `index.d.ts` must also declare both the type and variable declaration for classes as global:

```ts
import * as Edge from '@edge-runtime/primitives'

declare global {
  const fetch: typeof Edge.fetch
  const File: typeof Edge.File
  type File = Edge.File
  // etc...
}

**Comment by Kikobeats** [comment]
These global types are provided by TypeScript (from lib.dom.d.ts)

maybe something is wrong in your TS configuration?

**Comment by jedwards1211** [comment]
I understand that's a workaround, but it's not a proper solution... Vercel Edge Runtime will never be a DOM environment.  It doesn't have `window`, it doesn't have `document`, its `fetch` accepts nonstandard options, etc.

So `lib.dom.d.ts` would provide incorrect types for the Vercel Edge Runtime environment.

This is why `@cloudflare/workers-types` doesn't rely on `lib.dom.d.ts`; they declare global `fetch`, `File`, etc types own their own.  `@edge-runtime/types` will need to do this sooner or later to provide the best developer experience.

This is probably also why the docs page for `@edge-runtime/types` doesn't say anything about using `lib.dom.d.ts`.

**Comment by Kikobeats** [comment]
It's still unclear to me; This project, even not specifying `lib.dom.d.ts` as a type, `fetch` types are being resolved correctly:

<img width="922" alt="CleanShot 2023-08-17 at 11 01 39@2x" src="https://github.com/vercel/edge-runtime/assets/2096101/50f311eb-0208-4fa6-8866-cf8622e60428">
