### ISSUE TITLE
Expose cookie serialization functions.

### ISSUE THREAD

**Issue by bennor** [vercel/edge-runtime#518]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We have some advanced scenarios that require cookie manipulation in Next.js middleware (e.g. fixing domains coming from an origin server). At the moment we're hand rolling functions for these, but we're doubling up a bit because they already exist in `@edge-runtime/cookies`.

**Describe the solution you'd like**
It would be great if the serialization functions that underpin `@edge-runtime/cookies` were available to us:

- `stringifyCookie`
- `parseCookie`
- `parseSetCookie`

**Describe alternatives you've considered**
Writing our own, or importing from other libraries, but this increases bundle sizes unnecessarily (the above functions are already in our bundle, but we can't access them).

**Teachability, Documentation, Adoption, Migration Strategy**
N/A

**Comment by controversial** [comment]
You can access some of this functionality from the RequestCookies / ResponseCookies interfaces

For example, instead of `parseSetCookie`, you can use something like
```ts
import { ResponseCookies } from 'next/dist/server/web/spec-extension/cookies'; // or '@edge-runtime/cookies'

const headers = new Headers([['set-cookie', mySetCookieHeader]]);
const responseCookies = new ResponseCookies(headers);
const parsed = responseCookies.getAll();
```

And similar for `parseCookie`:
```ts
import { RequestCookies } from 'next/dist/server/web/spec-extension/cookies'; // or '@edge-runtime/cookies'

const headers = new Headers([['cookie', myCookieHeader]]);
const requestCookies = new RequestCookies(headers);
const parsed = requestCookies.getAll();
```
