### ISSUE TITLE
Include a key in process.versions for detecting edge runtime

### ISSUE THREAD

**Issue by controversial** [vercel/edge-runtime#527]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It’s difficult to for code to test/detect that it is running in the Vercel Edge Runtime.

**Describe the solution you'd like**
Define a key like `process.versions.vercelEdgeRuntime` (akin to `process.versions.node`)

**Describe alternatives you've considered**
Testing for the opposite (ie “we’re in the edge runtime if `!process.versions?.node`”) - this isn’t ideal because some code can run in more than two environments.

**Comment by Kikobeats** [comment]
Maybe this could be useful for your user case?
https://edge-runtime.vercel.app/features/available-apis#addressing-the-runtime

**Comment by controversial** [comment]
Don’t know how I missed that—that’s exactly what I’m looking for!

Thanks!
