### ISSUE TITLE
Primitives: event-target-shim causes issues w/ edge-runtime running on top of node

### ISSUE THREAD

**Issue by aplr** [vercel/edge-runtime#537]
## Bug Report

I lately ran into [an issue](https://github.com/connectrpc/connect-es/issues/749) which prevents using [`connect-es`](https://github.com/connectrpc/connect-es) in edge functions, including Next.js' middleware, due to [an issue with event-target-shim](https://github.com/mysticatea/event-target-shim/issues/61) which is used in `@edge-runtime/primitives`.

As this ponyfill is used for local dev environments and standalone builds of Next.js, the problem only becomes evident on these setups.

**Current behavior**

> Copied from referenced issues.

I try to use `connect-web` in the Next.js middleware. As Node APIs are not available there, using `connect-node` won't work.

I expect it to work, as the edge runtime seems to support all necessary features required by connect-web.

However, requests fail with the following error, leading me through `edge-runtime` into the packaged `event-target-shim`

```
- error Error [TypeError]: Cannot read properties of undefined (reading 'flags')
    at setRemoved (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334)
    at removeListenerAt (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334)
    at EventTarget.dispatchEvent (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334)
    at abortSignalAbort (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334)
    at AbortController.abort (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:970334)
    at done (webpack-internal:///(middleware)/./node_modules/@bufbuild/connect/dist/esm/protocol/run-call.js:103:24)
    at eval (webpack-internal:///(middleware)/./node_modules/@bufbuild/connect/dist/esm/protocol/run-call.js:33:9)
...
```

**Expected behavior/code**

Requests do not fail because of removing event listeners. See referenced issues.

**Possible solution**

Probably these issues should be fixed upstream, however it does not look like [event-target-shim](https://github.com/mysticatea/event-target-shim) is actively maintained.

As the event target API [was added to node in v15](https://nodejs.org/api/events.html#eventtarget-and-event-api), becoming stable in v15.4, it's available as long as you're not running a lower version, so probably it's possible to just conditionally use this shim, limiting the prone setups to node<15. Causes deviating implementation in `@edge-runtime/ponyfill` however.

I don't think it's an issue how `connect-es` uses the event target API. The issue is caused when removing an event listener in the listener callback, effectively manually creating a once-listener. This does not seem like some odd behaviour to me.

**Comment by Kikobeats** [comment]
It seems Node.js EventTarget and DOM EventTarget are not exactly the same but maybe we can drop the polyfill and everything work as desired.

I can't provide an ETA due we're shipping other things; Maybe you want to create a PR for this? 🙂

**Comment by aplr** [comment]
Hey @Kikobeats, sorry for not responding, I'm on vacation right now. Yea read about that at [node](https://nodejs.org/api/events.html#nodejs-eventtarget-vs-dom-eventtarget) and [mdn](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget?retiredLocale=de#browser_compatibility) docs, but yea, probably won't be an issue as the differences are more DOM-related. But yea, can't really tell how certain libraries use these APIs.

Ok that's a pragmatic approach, so Next.js does not support node 14 any more then?

**Comment by ddimaria** [comment]
Node v16 was problematic for me as well. v18 and v20 work fine though.
