### ISSUE TITLE
drop node16 support

### ISSUE THREAD

**Issue by Kikobeats** [vercel/edge-runtime#546]
- drop `@ungap/structured-clone`
- drop [`structuredClone`](https://github.com/vercel/edge-runtime/blob/7a79df9fd22811cb9d73cfbaea9e76689a5b426c/packages/primitives/src/primitives/structured-clone.js#L4)
- drop [undici](https://nodejs.org/api/globals.html#fetch)?
- drop `blob-polyfill`
- drop `formdata-node`
- drop getSetCookie [fallback](https://github.com/vercel/edge-runtime/pull/650/files#diff-a8d53f507783c1dd778999a6da3982d4e791b28705291d0f0a386552ff06f023R22)
- drop `toToReadable`
	-  introduced by: https://github.com/vercel/edge-runtime/pull/219.
	- use [`stream.Readable.fromWeb`](https://nodejs.org/api/stream.html#streamreadablefromwebreadablestream-options) instead.
- remove conditional assertions (find for `process.version`)
  - https://github.com/vercel/edge-runtime/blob/c2d9c3c7f8062a2787da69320875ac92145c61e9/packages/integration-tests/tests/blob.test.ts#L1
  - https://github.com/vercel/edge-runtime/blob/87a5b5ed3348036d0dce95caf787fd3f1ee43044/packages/integration-tests/test/body.test.ts#L1

**Comment by rnbrady** [comment]
@Kikobeats would this PR keep undici WebSockets? If so, any chance of a bump to undici@6?
