### ISSUE TITLE
Does @edge-runtime/types need additional dependencies or settings?

### ISSUE THREAD

**Issue by IanMitchell** [vercel/edge-runtime#56]
Hello! I'm trying to integrate with edge-runtime into my project monorepo, but I'm having a few issues getting started with the types package. When I follow the instructions on the website, I end up with undefined values for Request, CryptoKey, and other Edge Runtime items.

I tracked it down to having `"lib": ["ES2021"]` in my `tsconfig.json`, but removing it seems to let Node primitives bubble up. Should I be using the default `lib` in my TS config to mimic an edge runtime context?

**Comment by Kikobeats** [comment]
Hey @IanMitchell, sorry for the late response.

It should be work if you use the specific types package:
https://edge-runtime.vercel.app/packages/types.

Since this issue is from some time ago, I'm going to assume it's resolved with that.

Ping me back if something is not working as you expect 🙂
