### ISSUE TITLE
Why cannot my `fetch` API work in edge function?

### ISSUE THREAD

**Issue by gyhyfj** [vercel/edge-runtime#584]
My code in `/api/xxx.ts` is :
```ts
export const config = {
  runtime: 'edge',
}

export default async function handler(request: Request) {
  const cookies = request.headers.get('cookie')
  let body: any
  try {
    body = await request.json()
  } catch (e) {
    body = null
  }
  const clientInfo = {
    cookies,
    ...body,
  }

  try {
    await fetch('http://47.106.137.81:8001/api/landing', {
      method: 'POST',
      body: '{x:99}',
     headers: {
        'Content-Type': 'application/json;charset=utf-8;',
      },
     })
  } catch (err) {
    console.log('error', err)
  }

  return new Response(JSON.stringify(clientInfo), {
    status: 200,
    headers: {
      'content-type': 'application/json',
    },
  })
}
```
After deployed, these code works but that fetch api doesn't really work, my server side cannot get any request and if I try to print what that fetch api  got , I found it just get an empty Response object.

**Comment by Kikobeats** [comment]
fetch there is pretty much fetch from [undici](https://github.com/nodejs/undici)

can you try to use it standalone from a Serverless Function to see if your server is doing something?

**Comment by gyhyfj** [comment]
> fetch there is pretty much fetch from [undici](https://github.com/nodejs/undici)
> 
> can you try to use it standalone from a Serverless Function to see if your server is doing something?

Yes, my server works well, no matter testing by postman or testing locally by run `vercel dev`, my server can get request as expected. 
Besides, the code like 
```ts
fetch('http://47.106.137.81:8001/api/landing', {
      method: 'POST',
      body: '{x:99}',
     headers: {
        'Content-Type': 'application/json;charset=utf-8;',
      },
     }).then(res=>res.text()).then(console.log)
```
works well locally also, but would throw error in edge envrionment, because this fetch can only get an empty  Response object. My server api is an simple func , just print something and return `'123'` when get request .

**Comment by gyhyfj** [comment]
Just now I use `ofetch` to send request for test, throw an error in vercel log:
```bash
FetchError: [POST] "http://47.106.137.81:8001/api/landing": 403 Forbidden
    at (node_modules/.pnpm/ofetch@1.3.3/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:14)
    at (api/landing.js:21:8) {
  name: 'FetchError'
}
```

**Comment by gyhyfj** [comment]
I'm almost sure that vercel edge function doesn't allow `http` fectch, only `https` is allowed.

**Comment by hoqua** [comment]
@gyhyfj, have you found a solution to your problem?

**Comment by gyhyfj** [comment]
> @gyhyfj, have you found a solution to your problem?

No, do you encounter similar problem?
