### ISSUE TITLE
🙏`fetch` api doesn't work in edge function

### ISSUE THREAD

**Issue by gyhyfj** [vercel/edge-runtime#596]
## Bug Report

**Current behavior**

`fech` api can't work well in edge enviroment as expected.

**Expected behavior/code**

expect `fech` api to work well as in web environment or running `vercel dev` locally.

**Additional context/screenshots**

Here is a [minimal reproduct](https://github.com/gyhyfj/vercel-edge-fetch-reproduct).
This function is deployed at [https://test-peach-three.vercel.app/api/test](https://test-peach-three.vercel.app/api/test).

In this reproduct, I try to fetch [https://47.106.137.81:9001/api/test](https://47.106.137.81:9001/api/test) but failed in edge environment.

🙏 Can someone help me about this?

**Comment by gyhyfj** [comment]
I actually believe that the edge function didn't make a request because I don't see any new access records in my Linux server's Nginx logs.

**Comment by Kikobeats** [comment]
**local**

<img width="395" alt="CleanShot 2023-09-11 at 11 04 08@2x" src="https://github.com/vercel/edge-runtime/assets/2096101/b146f948-0f02-42b8-be72-b83df0bd9ce1">

**production**

![CleanShot 2023-09-11 at 11 13 28@2x](https://github.com/vercel/edge-runtime/assets/2096101/38a86098-4800-4dfd-afc6-ab0de1e4911c)

However, I can see sometimes `error code: 1003`:

![](https://global.discourse-cdn.com/cloudflare/original/3X/4/f/4fbb2cda5b1d14c175b42d563000f097c4ed7410.png)

is your service hosted in CloudFlare? It seems there are some protection to prevent direct IP access

**Comment by smaeda-ks** [comment]
@gyhyfj based on the situation, I don't think this is related to the Edge Runtime itself, but more of your origin configuration issue, specifically around security protections, as you mentioned.

I can't reproduce the error on https://test-peach-three.vercel.app/api/test anymore, but it's possible your origin server (or your hosting provider) was blocking our IPs at that time. Your hosting provider should be able to answer that.
