### ISSUE TITLE
Which functions and APIs advance the value returned by `Date.now`?

### ISSUE THREAD

**Issue by brettimus** [vercel/edge-runtime#628]
## Questions & Answers

One of the limitations of the Edge Runtime is that it does not advance the time returned by `Date.now` except for I/O operations.

The documentation only lists `fetch` as one of the functions that will advance the clock. Which other functions do this?

Context: I am trying to build latency tracking into functions inside an edge function, so knowing how long certain operations took is helpful. I'm in search of a hack to quickly trigger clock advancement, so I can track latency without adding too much noise (10s of ms is okay, but waiting on a roundtrip with fetch adds several hundred ms sometimes, which is not okay)

**Comment by Kikobeats** [comment]
Hello, that's accurate; it's a current limitation:
https://vercel.com/docs/functions/edge-functions/limitations#limited-date-api

The Edge Runtime is not implementing that limitation to don't make the implementation complex, but the limitation is there for any Vercel Edge Function.

**Comment by brettimus** [comment]
Hey sorry but that didn’t answer my question!

I was asking which other functions advance the clock. So far I discovered that fetch doesn’t advance the clock when it fails out of the gate, and setTimeout causes the value to move. 

Where can I find documentation on the functions that will affect Date.now

thanks again for responding so fast

**Comment by Kikobeats** [comment]
Just I/O operations advance the clock. Maybe your fetch is finishing too soon?
