### ISSUE TITLE
Response.redirect() fails to parse some URLs in production which parse successfully in local runtime

### ISSUE THREAD

**Issue by kcole93** [vercel/edge-runtime#663]
## Bug Report

**Current behavior**

`Response.redirect()` throws `TypeError: Failed to parse URL` when certain URIs (which can be used to successfully construct a URL in the local dev environment, in the browser console and in the Edge runtime) are passed to its `url` argument. In particular, I'm facing this issue when trying to redirect to such URLs using Edge Middleware:

```javascript
const exampleUrl = new URL('spotify:track:4cOdK2wGLETKBW3PvgPWqT') // Successfully constructs a URL
new Response.redirect(exampleUrl, 302) // Throws "TypeError: Failed to parse URL" in edge runtime
```
I'm also able to invoke `Response.redirect(exampleUrl, 302)` in the browser console without throwing a type error.

It should be noted that other URIs are parsed successfully, and it seems like those which manage to be parsed contain a "//" like "zotero://", "slack://" etc.

**Expected behavior/code**

I'd expect for `Response.redirect(exampleUrl, 302)` to successfully parse the URL and send a redirect response, provided the supplied URL parses correctly when using WebAPI's URL constructor and also given that the native WebAPI implementation of `Response.redirect()` does not throw a type error with these inputs.

**Comment by smaeda-ks** [comment]
@kcole93 Thanks for the report. We should be able to fix this in the next few weeks. I'll keep you updated.

**Comment by smaeda-ks** [comment]
@kcole93 This has been fixed. Thanks for reporting
