### ISSUE TITLE
cookie: `parseSetCookie` ignores `Max-Age` attribute

### ISSUE THREAD

**Issue by kosmotema** [vercel/edge-runtime#941]
## Bug Report

**Current behavior**

`parseSetCookie` ignores the Max-Age attribute when parsing a cookie. For example, this code:

```js
import { parseSetCookie } from "@edge-runtime/cookies";

console.log(parseSetCookie("foo=bar; Max-Age=86400; Path=/; SameSite=none; HttpOnly; Secure"));
```

will output the following to the console:

```js
{
  name: 'foo',
  value: 'bar',
  httpOnly: true,
  path: '/',
  sameSite: 'none',
  secure: true
}
```

**Expected behavior/code**

The above code sample should output:

```js
{
  name: 'foo',
  value: 'bar',
  httpOnly: true,
  maxAge: 86400,
  path: '/',
  sameSite: 'none',
  secure: true
}
```

**Possible solution**

Since the `Max-Age` attribute (unlike the others) contains a hyphen in [its name](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#max-agenumber), [here](https://github.com/vercel/edge-runtime/blob/ff6580581017970106097188fbd4c0197477428c/packages/cookies/src/serialize.ts#L64) should be something like `"max-age": maxage`

**Comment by sibiraj-s** [comment]
Made a fix https://github.com/vercel/edge-runtime/pull/995
